FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY ./monster_word_agent monster_word_agent
COPY assets assets

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT"]